name: im2alone
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  #network
  dio: ^5.3.2
  #localization
  easy_localization: ^3.0.2
  #state management
  get: ^4.6.5
  #caching
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  #utils
  flutter_svg: ^2.0.7

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
  fonts: 
      - family: Comfortaa
        fonts: 
          - asset: fonts/Comfortaa-Regular.ttf
          - asset: fonts/Comfortaa-Bold.ttf
            weight: 700
          - asset: fonts/Comfortaa-Light.ttf
            weight: 300
          - asset: fonts/Comfortaa-Medium.ttf
            weight: 500
          - asset: fonts/Comfortaa-SemiBold.ttf
            weight: 600