const Map<String, String> englishTranslate = {
  'APP_NAME': 'Im2Alone',
  'all_feeds': 'All Feeds',
  'my_diary': 'My Diary',
  'my_account': 'My Account',
  'settings': 'Settings',
  'delete': 'Delete',
  'logout': 'Logout',
  'write_diary': 'Write Diary',
  'login': 'Login',
  'register': 'Register',
  'email': 'Email',
  'username': 'Username',
  'publish_date': 'Publish Date',
  'password': 'Password',
  'forgot_password': 'Forgot Password',
  'search': 'Search',
  'view_more': 'View More',
  'search_hint': 'Search for a user',
  'write_feels': 'Write your feels...',
  'content_error': 'Please enter your feels!',
  'link': 'Link',
  'privacy': 'Privacy',
  'diary_added_successfully': 'Diary added successfully!',
  'diary_added_error': 'Diary added error!',
  'link_error': 'Please enter a valid spotify link!',
  'feel_link_error': 'Please enter a link!',
  'privacy_error': 'Please select a privacy!',
  'only_me': 'Only Me',
  'only_friends': 'Only Friends',
  'everyone': 'Everyone',
  'share': 'Share',
  'edit_profile': 'Edit Profile',
  'change_password': 'Change Password',
  'change_lang': 'Change Language',
  'no_diary': 'No Diary Yet',
  'user_not_found': 'User not found!',
  'search_friend': 'Search for a friend',
  'fullname': 'Fullname',
  'username_not_empty': 'Username cannot be empty!',
  'username_not_short': 'Username cannot be shorter than 4 characters!',
  'password_not_empty': 'Password cannot be empty!',
  'password_not_short': 'Password cannot be shorter than 6 characters!',
  'fullname_not_empty': 'Fullname cannot be empty!',
  'fullname_not_short': 'Fullname cannot be shorter than 4 characters!',
  'bio_not_empty': 'Bio cannot be empty!',
  'profile_not_saved': 'Profile cannot saved!',
  'profile_saved': 'Profile saved!',
  'save': 'Save',
  'password_change_success': 'Password changed successfully!',
  'password_change_error': 'Password changed error!',
  'confirm_password': 'Confirm Password',
  'new_password': 'New Password',
  'password_not_match': 'Passwords do not match!',
};
