const Map<String, String> englishTranslate = {
  'APP_NAME': 'Im2Alone',
  'all_feeds': 'All Feeds',
  'my_diary': 'My Diary',
  'my_account': 'My Account',
  'settings': 'Settings',
  'delete': 'Delete',
  'logout': 'Logout',
  'write_diary': 'Write Diary',
  'login': 'Login',
  'register': 'Register',
  'email': 'Email',
  'username': 'Username',
  'publish_date': 'Publish Date',
  'password': 'Password',
  'forgot_password': 'Forgot Password',
  'search': 'Search',
  'view_more': 'View More',
  'views': 'views',
  'search_hint': 'Search for a user',
  'write_feels': 'Write your feels...',
  'content_error': 'Please enter your feels!',
  'link': 'Song Link',
  'link_hint': 'Leave a spotify link to remember these feelings dude.',
  'privacy': 'Privacy',
  'diary_added_successfully': 'Diary added successfully!',
  'diary_added_error': 'Diary added error!',
  'link_error': 'Please enter a valid spotify link!',
  'feel_link_error': 'Please enter a link!',
  'privacy_error': 'Please select a privacy!',
  'only_me': 'Only Me',
  'only_friends': 'Only Friends',
  'everyone': 'Everyone',
  'share': 'Share',
  'edit_profile': 'Edit Profile',
  'change_password': 'Change Password',
  'change_lang': 'Change Language',
  'no_diary': 'No Diary Yet',
  'user_not_found': 'User not found!',
  'search_friend': 'Search for a friend',
  'fullname': 'Fullname',
  'username_not_empty': 'Username cannot be empty!',
  'username_not_short': 'Username cannot be shorter than 4 characters!',
  'password_not_empty': 'Password cannot be empty!',
  'password_not_short': 'Password cannot be shorter than 6 characters!',
  'fullname_not_empty': 'Fullname cannot be empty!',
  'fullname_not_short': 'Fullname cannot be shorter than 4 characters!',
  'bio_not_empty': 'Bio cannot be empty!',
  'profile_not_saved': 'Profile cannot saved!',
  'profile_saved': 'Profile saved!',
  'avatar_saved': 'Profile picture updated!',
  'avatar_not_saved': 'Profile picture could not be updated!',
  'save': 'Save',
  'password_change_success': 'Password changed successfully!',
  'password_change_error': 'Password changed error!',
  'confirm_password': 'Confirm Password',
  'new_password': 'New Password',
  'password_not_match': 'Passwords do not match!',
  'english': 'English',
  'turkish': 'Turkish',
  'cancel': 'Cancel',
  'add_friend': 'Add Friend',
  'delete_friend': 'Delete Friend',
  'friend_request_sent': 'Friend request sent!',
  'friend_request_not_sent': 'Friend request not sent!',
  'friend_deleted': 'Friend deleted!',
  'friend_not_deleted': 'Friend not deleted!',
  'friend_request_sended': 'Friend request sended',
  'friend_requests': 'Friend Requests',
  'no_friend_requests': 'No friend requests yet',
  'sent_you_friend_request': 'sent you a friend request',
  'accept': 'Accept',
  'ignore': 'Ignore',
  'error_accepting_friend_request': 'Error accepting friend request!',
  'error_ignoring_friend_request': 'Error ignoring friend request!',
  'diarys': 'Diarys',
  'followers': 'Followers',
  'following': 'Following',
  'followings': 'Following',
  'no_followers': 'No followers yet',
  'no_following': 'Not following anyone yet',
  'birthday': 'Birthday',
  'real_name': 'Real Name',
  'done': 'Done',
  'male': 'Male',
  'female': 'Female',
  'unisex': 'Other',
  'gender': 'Gender',
  "register_success": "Register success!",
  "gender_error": "Gender cannot be empty",
  "birthday_error": "Birthday cannot be empty",
  "email_error": "Email cannot be empty",
  "email_not_valid": "Email is not valid",
  "realname_error": "Realname cannot be empty",
  "password_error": "Password cannot be empty",
  "password_short": "Password cannot be shorter than 6 characters",
  "username_error": "Username cannot be empty",
  "username_short": "Username cannot be shorter than 4 characters",
  'report': 'Report',
  'report_user': 'Report User',
  'block': 'Block',
  'delete_account': 'Delete Account',
  'delete_account_confirm_title': 'Delete your account?',
  'delete_account_confirm_body':
      'Your account, diaries, friendships and all your data will be permanently deleted. This cannot be undone.',
  'session_expired': 'Your session has expired, please log in again.',
  'account_deleted': 'Your account has been deleted.',
  'account_delete_failed': 'Could not delete account, please try again.',
  'account_delete_wrong_password': 'Wrong password, account was not deleted.',
  'unblock': 'Unblock',
  'block_user_confirm_title': 'Block this user?',
  'block_user_confirm_body':
      'They will no longer be able to contact you, see your diaries, or find you in search.',
  'user_blocked': 'User blocked.',
  'user_block_failed': 'Could not block user.',
  'user_unblocked': 'User unblocked.',
  'user_unblock_failed': 'Could not unblock user.',
  'blocked_users': 'Blocked Users',
  'no_blocked_users': "You haven't blocked anyone.",
  'report_reason': 'Reason',
  'report_reason_nudity': 'Nudity / Sexual content',
  'report_reason_harassment': 'Harassment / Bullying',
  'report_reason_spam': 'Spam',
  'report_reason_violence': 'Violence',
  'report_reason_hate_speech': 'Hate speech',
  'report_reason_other': 'Other',
  'report_description_hint': 'Add details (optional)',
  'submit_report': 'Submit Report',
  'report_reason_error': 'Please select a reason',
  'report_sent': "Report sent. We'll review it within 24 hours.",
  'report_send_failed': 'Could not send report.',
  'terms_of_service': 'Terms of Service',
  'support': 'Support',
  'i_agree_to_terms': 'I agree to the ',
  'terms_required': 'You must accept the Terms of Service to continue',
  'error': 'Something went wrong.',
  'network_timeout_error': 'Connection timed out. Please check your internet and try again.',
  'network_connection_error': 'No internet connection. Please check your connection and try again.',
  'network_server_error': 'Something went wrong on our end. Please try again shortly.',
  'network_unknown_error': 'Something went wrong. Please try again.',
  'diary_queued_offline': "You're offline — your diary was saved and will be sent automatically once you're back online.",
  'offline_showing_cached': "You're offline — showing your last saved diaries.",
  'pending_diaries_sent': 'Your pending diary entries have been sent.',
  'pending_diary_badge': 'Waiting to send',
};
