import 'package:get/get.dart';

class ProductTranslations extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          'APP_NAME': 'Im2Alone',
          'all_feeds': 'All Feeds',
          'my_diary': 'My Diary',
          'my_account': 'My Account',
          'settings': 'Settings',
          'delete': 'Delete',
          'logout': 'Logout',
          'write_diary': 'Write Diary',
          'login': 'Login',
          'register': 'Register',
          'email': 'Email',
          'username': 'Username',
          'publish_date': 'Publish Date',
          'password': 'Password',
          'forgot_password': 'Forgot Password',
          'search': 'Search',
          'view_more': 'View More',
          'search_hint': 'Search for a user',
          'write_feels': 'Write your feels...',
          'content_error': 'Please enter your feels!',
          'link': 'Link',
          'privacy': 'Privacy',
          'diary_added_successfully': 'Diary added successfully!',
          'diary_added_error': 'Diary added error!',
          'link_error': 'Please enter a valid spotify link!',
          'feel_link_error': 'Please enter a link!',
          'privacy_error': 'Please select a privacy!',
          'only_me': 'Only Me',
          'only_friends': 'Only Friends',
          'everyone': 'Everyone',
          'share': 'Share',
          'edit_profile': 'Edit Profile',
          'change_password': 'Change Password',
          'change_lang': 'Change Language',
          'no_diary': 'No Diary Yet',
        },
        'tr_TR': {
          'no_diary': 'Henüz Günlük Yok',
          'change_lang': 'Dili Değiştir',
          'change_password': 'Şifre Değiştir',
          'APP_NAME': 'Im2Alone',
          'all_feeds': 'Gönderiler',
          'my_diary': 'Günlüğüm',
          'my_account': 'Hesabım',
          'settings': 'Ayarlar',
          'delete': 'Sil',
          'logout': 'Çıkış Yap',
          'write_diary': 'Günlük Yaz',
          'login': 'Giriş Yap',
          'register': 'Kayıt Ol',
          'email': 'E-posta',
          'username': 'Kullanıcı Adı',
          'password': 'Şifre',
          'forgot_password': 'Şifremi Unuttum',
          'search': 'Ara',
          'link': 'Link',
          'publish_date': 'Yayınlanma Tarihi',
          'diary_added_successfully': 'Günlük başarıyla eklendi!',
          'diary_added_error': 'Günlük eklenirken bir hata oluştu!',
          'privacy': 'Gizlilik',
          'view_more': 'Daha Fazla',
          'search_hint': 'Bir kullanıcı ara',
          'write_feels': 'Neler hissediyorsun?',
          'content_error': 'Lütfen hislerinizi yazınız!',
          'link_error': 'Lütfen geçerli bir spotify linki giriniz!',
          'feel_link_error': 'Lütfen bir link giriniz!',
          'privacy_error': 'Lütfen bir gizlilik seçiniz!',
          'only_me': 'Sadece Ben',
          'only_friends': 'Sadece Arkadaşlarım',
          'everyone': 'Herkes',
          'share': 'Paylaş',
          'edit_profile': 'Profili Düzenle',
        },
      };
}
