const Map<String, String> turkishTranslate = {
  'save': 'Kaydet',
  'profile_not_saved': 'Profil kaydedilemedi!',
  'profile_saved': 'Profil kaydedildi!',
  'avatar_saved': 'Profil fotoğrafı güncellendi!',
  'avatar_not_saved': 'Profil fotoğrafı güncellenemedi!',
  'bio_not_empty': 'Bio boş olamaz!',
  'fullname_not_short': 'Ad Soyad 4 karakterden kısa olamaz!',
  'fullname_not_empty': 'Ad Soyad boş olamaz!',
  'password_not_short': 'Şifre 6 karakterden kısa olamaz!',
  'password_not_empty': 'Şifre boş olamaz!',
  'username_not_short': 'Kullanıcı adı 4 karakterden kısa olamaz!',
  'username_not_empty': 'Kullanıcı adı boş olamaz!',
  'fullname': 'Ad Soyad',
  'search_friend': 'Bir arkadaş ara',
  'user_not_found': 'Kullanıcı bulunamadı!',
  'no_diary': 'Henüz Günlük Yok',
  'change_lang': 'Dili Değiştir',
  'change_password': 'Şifre Değiştir',
  'APP_NAME': 'Im2Alone',
  'all_feeds': 'Gönderiler',
  'my_diary': 'Günlüğüm',
  'my_account': 'Hesabım',
  'settings': 'Ayarlar',
  'delete': 'Sil',
  'logout': 'Çıkış Yap',
  'write_diary': 'Günlük Yaz',
  'login': 'Giriş Yap',
  'register': 'Kayıt Ol',
  'email': 'E-posta',
  'username': 'Kullanıcı Adı',
  'password': 'Şifre',
  'forgot_password': 'Şifremi Unuttum',
  'search': 'Ara',
  'link': 'Şarkı Linki',
  'link_hint': 'Bu hisleri hatırlamak için bir spotify linki bırak dostum.',
  'publish_date': 'Yayınlanma Tarihi',
  'diary_added_successfully': 'Günlük başarıyla eklendi!',
  'diary_added_error': 'Günlük eklenirken bir hata oluştu!',
  'privacy': 'Gizlilik',
  'view_more': 'Daha Fazla',
  'views': 'görüntülenme',
  'search_hint': 'Bir kullanıcı ara',
  'write_feels': 'Neler hissediyorsun?',
  'content_error': 'Lütfen hislerinizi yazınız!',
  'link_error': 'Lütfen geçerli bir spotify linki giriniz!',
  'feel_link_error': 'Lütfen bir link giriniz!',
  'privacy_error': 'Lütfen bir gizlilik seçiniz!',
  'only_me': 'Sadece Ben',
  'only_friends': 'Sadece Arkadaşlarım',
  'everyone': 'Herkes',
  'share': 'Paylaş',
  'edit_profile': 'Profili Düzenle',
  'password_change_success': 'Şifre başarıyla değiştirildi!',
  'password_change_error': 'Şifre değiştirilirken bir hata oluştu!',
  'confirm_password': 'Şifre Tekrar',
  'new_password': 'Yeni Şifre',
  'password_not_match': 'Şifreler eşleşmiyor!',
  'english': 'İngilizce',
  'turkish': 'Türkçe',
  'cancel': 'Çık',
  'add_friend': 'Arkadaş Ekle',
  'delete_friend': 'Arkadaş Sil',
  'friend_request_sent': 'Arkadaşlık isteği gönderildi!',
  'friend_request_not_sent': 'Arkadaşlık isteği gönderilemedi!',
  'friend_deleted': 'Arkadaş silindi!',
  'friend_not_deleted': 'Arkadaş silinemedi!',
  'friend_request_sended': 'Arkadaşlık isteği gönderildi',
  'friend_requests': 'Arkadaşlık İstekleri',
  'no_friend_requests': 'Henüz arkadaşlık isteği yok',
  'sent_you_friend_request': 'sana arkadaşlık isteği gönderdi',
  'accept': 'Kabul Et',
  'ignore': 'Reddet',
  'error_accepting_friend_request': 'Arkadaşlık isteği kabul edilirken bir hata oluştu!',
  'error_ignoring_friend_request': 'Arkadaşlık isteği reddedilirken bir hata oluştu!',
  'diarys': 'Günlükler',
  'followers': 'Takipçi',
  'followings': 'Takip',
  'no_followers': 'Henüz takipçin yok',
  'no_following': 'Henüz kimseyi takip etmiyorsun',
  'birthday': 'Doğum Tarihi',
  'real_name': 'Ad Soyad',
  'done': 'Tamam',
  'male': 'Erkek',
  'female': 'Kadın',
  'unisex': 'Diğer',
  'gender': 'Cinsiyet',
  "register_success": "Kayıt başarılı!",
  "gender_error": "Cinsiyet boş olamaz",
  "birthday_error": "Doğum tarihi boş olamaz",
  "email_error": "E-posta boş olamaz",
  "email_not_valid": "E-posta geçerli değil",
  "realname_error": "Ad Soyad boş olamaz",
  "password_error": "Şifre boş olamaz",
  "password_short": "Şifre 6 karakterden kısa olamaz",
  "username_error": "Kullanıcı adı boş olamaz",
  "username_short": "Kullanıcı adı 4 karakterden kısa olamaz",
  'report': 'Şikayet Et',
  'report_user': 'Kullanıcıyı Şikayet Et',
  'block': 'Engelle',
  'delete_account': 'Hesabı Sil',
  'delete_account_confirm_title': 'Hesabın silinsin mi?',
  'delete_account_confirm_body':
      'Hesabın, günlüklerin, arkadaşlıkların ve tüm verilerin kalıcı olarak silinecek. Bu işlem geri alınamaz.',
  'account_deleted': 'Hesabın silindi.',
  'account_delete_failed': 'Hesap silinemedi, lütfen tekrar dene.',
  'account_delete_wrong_password': 'Şifre yanlış, hesap silinmedi.',
  'unblock': 'Engeli Kaldır',
  'block_user_confirm_title': 'Bu kullanıcıyı engellemek istiyor musunuz?',
  'block_user_confirm_body':
      'Bu kullanıcı artık sizinle iletişime geçemez, günlüklerinizi göremez ve aramada sizi bulamaz.',
  'user_blocked': 'Kullanıcı engellendi.',
  'user_block_failed': 'Kullanıcı engellenemedi.',
  'user_unblocked': 'Kullanıcının engeli kaldırıldı.',
  'user_unblock_failed': 'Engel kaldırılamadı.',
  'blocked_users': 'Engellenen Kullanıcılar',
  'no_blocked_users': 'Henüz kimseyi engellemediniz.',
  'report_reason': 'Sebep',
  'report_reason_nudity': 'Müstehcen / Cinsel İçerik',
  'report_reason_harassment': 'Taciz / Zorbalık',
  'report_reason_spam': 'Spam',
  'report_reason_violence': 'Şiddet',
  'report_reason_hate_speech': 'Nefret Söylemi',
  'report_reason_other': 'Diğer',
  'report_description_hint': 'Detay ekleyin (opsiyonel)',
  'submit_report': 'Şikayeti Gönder',
  'report_reason_error': 'Lütfen bir sebep seçin',
  'report_sent': 'Şikayetiniz alındı. 24 saat içinde incelenecektir.',
  'report_send_failed': 'Şikayet gönderilemedi.',
  'terms_of_service': 'Kullanım Şartları',
  'support': 'Destek',
  'i_agree_to_terms': 'Kabul ediyorum: ',
  'terms_required': 'Devam etmek için Kullanım Şartlarını kabul etmelisiniz',
  'error': 'Bir şeyler ters gitti.',
  'network_timeout_error': 'Bağlantı zaman aşımına uğradı. İnternetinizi kontrol edip tekrar deneyin.',
  'network_connection_error': 'İnternet bağlantısı yok. Bağlantınızı kontrol edip tekrar deneyin.',
  'network_server_error': 'Sunucu tarafında bir sorun oluştu. Lütfen kısa süre sonra tekrar deneyin.',
  'network_unknown_error': 'Bir şeyler ters gitti. Lütfen tekrar deneyin.',
  'diary_queued_offline': 'Çevrimdışısınız — günlüğünüz kaydedildi, bağlantı gelince otomatik gönderilecek.',
  'offline_showing_cached': 'Çevrimdışısınız — son kaydedilen günlükleriniz gösteriliyor.',
  'pending_diaries_sent': 'Bekleyen günlükleriniz gönderildi.',
  'pending_diary_badge': 'Gönderim Bekliyor',
};
