const Map<String, String> turkishTranslate = {
  'save': 'Kaydet',
  'profile_not_saved': 'Profil kaydedilemedi!',
  'profile_saved': 'Profil kaydedildi!',
  'bio_not_empty': 'Bio boş olamaz!',
  'fullname_not_short': 'Ad Soyad 4 karakterden kısa olamaz!',
  'fullname_not_empty': 'Ad Soyad boş olamaz!',
  'password_not_short': 'Şifre 6 karakterden kısa olamaz!',
  'password_not_empty': 'Şifre boş olamaz!',
  'username_not_short': 'Kullanıcı adı 4 karakterden kısa olamaz!',
  'username_not_empty': 'Kullanıcı adı boş olamaz!',
  'fullname': 'Ad Soyad',
  'search_friend': 'Bir arkadaş ara',
  'user_not_found': 'Kullanıcı bulunamadı!',
  'no_diary': 'Henüz Günlük Yok',
  'change_lang': 'Dili Değiştir',
  'change_password': 'Şifre Değiştir',
  'APP_NAME': 'Im2Alone',
  'all_feeds': 'Gönderiler',
  'my_diary': 'Günlüğüm',
  'my_account': 'Hesabım',
  'settings': 'Ayarlar',
  'delete': 'Sil',
  'logout': 'Çıkış Yap',
  'write_diary': 'Günlük Yaz',
  'login': 'Giriş Yap',
  'register': 'Kayıt Ol',
  'email': 'E-posta',
  'username': 'Kullanıcı Adı',
  'password': 'Şifre',
  'forgot_password': 'Şifremi Unuttum',
  'search': 'Ara',
  'link': 'Link',
  'publish_date': 'Yayınlanma Tarihi',
  'diary_added_successfully': 'Günlük başarıyla eklendi!',
  'diary_added_error': 'Günlük eklenirken bir hata oluştu!',
  'privacy': 'Gizlilik',
  'view_more': 'Daha Fazla',
  'search_hint': 'Bir kullanıcı ara',
  'write_feels': 'Neler hissediyorsun?',
  'content_error': 'Lütfen hislerinizi yazınız!',
  'link_error': 'Lütfen geçerli bir spotify linki giriniz!',
  'feel_link_error': 'Lütfen bir link giriniz!',
  'privacy_error': 'Lütfen bir gizlilik seçiniz!',
  'only_me': 'Sadece Ben',
  'only_friends': 'Sadece Arkadaşlarım',
  'everyone': 'Herkes',
  'share': 'Paylaş',
  'edit_profile': 'Profili Düzenle',
  'password_change_success': 'Şifre başarıyla değiştirildi!',
  'password_change_error': 'Şifre değiştirilirken bir hata oluştu!',
  'confirm_password': 'Şifre Tekrar',
  'new_password': 'Yeni Şifre',
  'password_not_match': 'Şifreler eşleşmiyor!',
  'english': 'İngilizce',
  'turkish': 'Türkçe',
  'cancel': 'Çık',
  'add_friend': 'Arkadaş Ekle',
  'delete_friend': 'Arkadaş Sil',
  'friend_request_sent': 'Arkadaşlık isteği gönderildi!',
  'friend_request_not_sent': 'Arkadaşlık isteği gönderilemedi!',
  'friend_deleted': 'Arkadaş silindi!',
  'friend_not_deleted': 'Arkadaş silinemedi!',
};
